// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $admin_actions from "./routes/admin/actions.ts";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $api_interactions from "./routes/api/interactions.ts";
import * as $api_messages from "./routes/api/messages.ts";
import * as $api_patterns_id_ from "./routes/api/patterns/[id].ts";
import * as $api_patterns_index from "./routes/api/patterns/index.ts";
import * as $api_patterns_stats from "./routes/api/patterns/stats.ts";
import * as $api_patterns_test from "./routes/api/patterns/test.ts";
import * as $api_reminders_id_ from "./routes/api/reminders/[id].ts";
import * as $api_reminders_bulk from "./routes/api/reminders/bulk.ts";
import * as $api_reminders_index from "./routes/api/reminders/index.ts";
import * as $api_reminders_stats from "./routes/api/reminders/stats.ts";
import * as $api_reminders_templates from "./routes/api/reminders/templates.ts";
import * as $api_reminders_templates_id_ from "./routes/api/reminders/templates/[id].ts";
import * as $api_scheduler_status from "./routes/api/scheduler/status.ts";
import * as $api_webhook from "./routes/api/webhook.ts";
import * as $auth_callback from "./routes/auth/callback.ts";
import * as $auth_discord from "./routes/auth/discord.ts";
import * as $index from "./routes/index.tsx";
import * as $reminders_history from "./routes/reminders/history.tsx";
import * as $reminders_index from "./routes/reminders/index.tsx";
import * as $reminders_manage from "./routes/reminders/manage.tsx";
import * as $reminders_new from "./routes/reminders/new.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/admin/actions.ts": $admin_actions,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/api/interactions.ts": $api_interactions,
    "./routes/api/messages.ts": $api_messages,
    "./routes/api/patterns/[id].ts": $api_patterns_id_,
    "./routes/api/patterns/index.ts": $api_patterns_index,
    "./routes/api/patterns/stats.ts": $api_patterns_stats,
    "./routes/api/patterns/test.ts": $api_patterns_test,
    "./routes/api/reminders/[id].ts": $api_reminders_id_,
    "./routes/api/reminders/bulk.ts": $api_reminders_bulk,
    "./routes/api/reminders/index.ts": $api_reminders_index,
    "./routes/api/reminders/stats.ts": $api_reminders_stats,
    "./routes/api/reminders/templates.ts": $api_reminders_templates,
    "./routes/api/reminders/templates/[id].ts": $api_reminders_templates_id_,
    "./routes/api/scheduler/status.ts": $api_scheduler_status,
    "./routes/api/webhook.ts": $api_webhook,
    "./routes/auth/callback.ts": $auth_callback,
    "./routes/auth/discord.ts": $auth_discord,
    "./routes/index.tsx": $index,
    "./routes/reminders/history.tsx": $reminders_history,
    "./routes/reminders/index.tsx": $reminders_index,
    "./routes/reminders/manage.tsx": $reminders_manage,
    "./routes/reminders/new.tsx": $reminders_new,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
